version: '3'
services:
  # alternative rtsp-server: can be used with rtsp commands in "x11-entry.sh"
  # configuration in "rtsp-simple-server.yml"
  # rtsp-simple-server:
  #   image: aler9/rtsp-simple-server
  #   network_mode: "host"
  #   ports: 
  #     - "8000:8000"
  #     - "8001:8001"
  #     - "8554:8554"
  #   volumes:
  #     - ./docker/rtsp-simple-server.yml:/rtsp-simple-server.yml"
  rgbdtoolkits:
    image: aivero-rgbd-toolkit:latest
    # remove "network_mode: host" if using rtsp-simple-server
    network_mode: "host"
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      # Dockerfile_dev contains additional steps for debugging the used components
      # dockerfile: ./docker/Dockerfile_dev
    environment:
      - DISPLAY=${DISPLAY}
      - HOSTNAME=${HOSTNAME}
    volumes:
      - '/dev:/dev'
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/home/lyonn/.Xauthority
    privileged: true
    # alternative entrypoint can be defined here
    #command: ["/bin/bash","x11-entry.sh"]